
	// ************************************************************
	// Generated by pnp2ts - do not edit
	// www.koksmat.com
	// v0.1.0
	// ************************************************************
	

	
	
	
	
import { listName as BuildingsList,dependencies as BuildingsDependencies } from "./Buildings";
import { listName as CateringOrdersList,dependencies as CateringOrdersDependencies } from "./CateringOrders";
import { listName as CateringOrdersInvoicesList,dependencies as CateringOrdersInvoicesDependencies } from "./CateringOrdersInvoices";
import { listName as CateringOrdersItemsList,dependencies as CateringOrdersItemsDependencies } from "./CateringOrdersItems";
import { listName as CateringOrdersWorkOrdersList,dependencies as CateringOrdersWorkOrdersDependencies } from "./CateringOrdersWorkOrders";
import { listName as CateringProvidersList,dependencies as CateringProvidersDependencies } from "./CateringProviders";
import { listName as CavaSAPreportList,dependencies as CavaSAPreportDependencies } from "./CavaSAPreport";
import { listName as CompaniesList,dependencies as CompaniesDependencies } from "./Companies";
import { listName as CountriesList,dependencies as CountriesDependencies } from "./Countries";
import { listName as CurrencyList,dependencies as CurrencyDependencies } from "./Currency";
import { listName as DesksList,dependencies as DesksDependencies } from "./Desks";
import { listName as DocumentsList,dependencies as DocumentsDependencies } from "./Documents";
import { listName as EventsList,dependencies as EventsDependencies } from "./Events";
import { listName as EventTrackingList,dependencies as EventTrackingDependencies } from "./EventTracking";
import { listName as FloorsList,dependencies as FloorsDependencies } from "./Floors";
import { listName as FormTemplatesList,dependencies as FormTemplatesDependencies } from "./FormTemplates";
import { listName as ItemGroupsList,dependencies as ItemGroupsDependencies } from "./ItemGroups";
import { listName as ItemsList,dependencies as ItemsDependencies } from "./Items";
import { listName as KeyValuesList,dependencies as KeyValuesDependencies } from "./KeyValues";
import { listName as LocationsList,dependencies as LocationsDependencies } from "./Locations";
import { listName as LunchMenuList,dependencies as LunchMenuDependencies } from "./LunchMenu";
import { listName as Pricelists2List,dependencies as Pricelists2Dependencies } from "./Pricelists2";
import { listName as RoomSitesList,dependencies as RoomSitesDependencies } from "./RoomSites";
import { listName as RoomsList,dependencies as RoomsDependencies } from "./Rooms";
import { listName as SharedMailboxesOwnersList,dependencies as SharedMailboxesOwnersDependencies } from "./SharedMailboxesOwners";
import { listName as SharedMailboxOwnersList,dependencies as SharedMailboxOwnersDependencies } from "./SharedMailboxOwners";
import { listName as SiteAssetsList,dependencies as SiteAssetsDependencies } from "./SiteAssets";
import { listName as SitePagesList,dependencies as SitePagesDependencies } from "./SitePages";
import { listName as StyleLibraryList,dependencies as StyleLibraryDependencies } from "./StyleLibrary";
import { listName as TestChangesList,dependencies as TestChangesDependencies } from "./TestChanges";
import { listName as UseCasesList,dependencies as UseCasesDependencies } from "./UseCases";
import { listName as WorkspacesList,dependencies as WorkspacesDependencies } from "./Workspaces";
export function map(){

	const dependencies = []

dependencies.push({listName : BuildingsList,
dependencies:  BuildingsDependencies }) 
dependencies.push({listName : CateringOrdersList,
dependencies:  CateringOrdersDependencies }) 
dependencies.push({listName : CateringOrdersInvoicesList,
dependencies:  CateringOrdersInvoicesDependencies }) 
dependencies.push({listName : CateringOrdersItemsList,
dependencies:  CateringOrdersItemsDependencies }) 
dependencies.push({listName : CateringOrdersWorkOrdersList,
dependencies:  CateringOrdersWorkOrdersDependencies }) 
dependencies.push({listName : CateringProvidersList,
dependencies:  CateringProvidersDependencies }) 
dependencies.push({listName : CavaSAPreportList,
dependencies:  CavaSAPreportDependencies }) 
dependencies.push({listName : CompaniesList,
dependencies:  CompaniesDependencies }) 
dependencies.push({listName : CountriesList,
dependencies:  CountriesDependencies }) 
dependencies.push({listName : CurrencyList,
dependencies:  CurrencyDependencies }) 
dependencies.push({listName : DesksList,
dependencies:  DesksDependencies }) 
dependencies.push({listName : DocumentsList,
dependencies:  DocumentsDependencies }) 
dependencies.push({listName : EventsList,
dependencies:  EventsDependencies }) 
dependencies.push({listName : EventTrackingList,
dependencies:  EventTrackingDependencies }) 
dependencies.push({listName : FloorsList,
dependencies:  FloorsDependencies }) 
dependencies.push({listName : FormTemplatesList,
dependencies:  FormTemplatesDependencies }) 
dependencies.push({listName : ItemGroupsList,
dependencies:  ItemGroupsDependencies }) 
dependencies.push({listName : ItemsList,
dependencies:  ItemsDependencies }) 
dependencies.push({listName : KeyValuesList,
dependencies:  KeyValuesDependencies }) 
dependencies.push({listName : LocationsList,
dependencies:  LocationsDependencies }) 
dependencies.push({listName : LunchMenuList,
dependencies:  LunchMenuDependencies }) 
dependencies.push({listName : Pricelists2List,
dependencies:  Pricelists2Dependencies }) 
dependencies.push({listName : RoomSitesList,
dependencies:  RoomSitesDependencies }) 
dependencies.push({listName : RoomsList,
dependencies:  RoomsDependencies }) 
dependencies.push({listName : SharedMailboxesOwnersList,
dependencies:  SharedMailboxesOwnersDependencies }) 
dependencies.push({listName : SharedMailboxOwnersList,
dependencies:  SharedMailboxOwnersDependencies }) 
dependencies.push({listName : SiteAssetsList,
dependencies:  SiteAssetsDependencies }) 
dependencies.push({listName : SitePagesList,
dependencies:  SitePagesDependencies }) 
dependencies.push({listName : StyleLibraryList,
dependencies:  StyleLibraryDependencies }) 
dependencies.push({listName : TestChangesList,
dependencies:  TestChangesDependencies }) 
dependencies.push({listName : UseCasesList,
dependencies:  UseCasesDependencies }) 
dependencies.push({listName : WorkspacesList,
dependencies:  WorkspacesDependencies }) 


	return dependencies
}

