
	// ************************************************************
	// Generated by pnp2ts - do not edit
	// www.koksmat.com
	// v0.1.0
	// ************************************************************
	

	
	
	
	
import { listName as DocumentsList,dependencies as DocumentsDependencies } from "./Documents";
import { listName as EnvironmentsList,dependencies as EnvironmentsDependencies } from "./Environments";
import { listName as EpicsList,dependencies as EpicsDependencies } from "./Epics";
import { listName as EventsList,dependencies as EventsDependencies } from "./Events";
import { listName as FeaturesList,dependencies as FeaturesDependencies } from "./Features";
import { listName as FormTemplatesList,dependencies as FormTemplatesDependencies } from "./FormTemplates";
import { listName as IssuetrackerList,dependencies as IssuetrackerDependencies } from "./Issuetracker";
import { listName as PackagesList,dependencies as PackagesDependencies } from "./Packages";
import { listName as ProblemTrackerList,dependencies as ProblemTrackerDependencies } from "./ProblemTracker";
import { listName as ReleasesList,dependencies as ReleasesDependencies } from "./Releases";
import { listName as RequesttrackerList,dependencies as RequesttrackerDependencies } from "./Requesttracker";
import { listName as ServicesList,dependencies as ServicesDependencies } from "./Services";
import { listName as SiteAssetsList,dependencies as SiteAssetsDependencies } from "./SiteAssets";
import { listName as SitePagesList,dependencies as SitePagesDependencies } from "./SitePages";
import { listName as StyleLibraryList,dependencies as StyleLibraryDependencies } from "./StyleLibrary";
import { listName as UserProfilesList,dependencies as UserProfilesDependencies } from "./UserProfiles";
import { listName as UserVoiceList,dependencies as UserVoiceDependencies } from "./UserVoice";
import { listName as UserInformationListList,dependencies as UserInformationListDependencies } from "./UserInformationList";
export function map(){

	const dependencies = []

dependencies.push({listName : DocumentsList,
dependencies:  DocumentsDependencies }) 
dependencies.push({listName : EnvironmentsList,
dependencies:  EnvironmentsDependencies }) 
dependencies.push({listName : EpicsList,
dependencies:  EpicsDependencies }) 
dependencies.push({listName : EventsList,
dependencies:  EventsDependencies }) 
dependencies.push({listName : FeaturesList,
dependencies:  FeaturesDependencies }) 
dependencies.push({listName : FormTemplatesList,
dependencies:  FormTemplatesDependencies }) 
dependencies.push({listName : IssuetrackerList,
dependencies:  IssuetrackerDependencies }) 
dependencies.push({listName : PackagesList,
dependencies:  PackagesDependencies }) 
dependencies.push({listName : ProblemTrackerList,
dependencies:  ProblemTrackerDependencies }) 
dependencies.push({listName : ReleasesList,
dependencies:  ReleasesDependencies }) 
dependencies.push({listName : RequesttrackerList,
dependencies:  RequesttrackerDependencies }) 
dependencies.push({listName : ServicesList,
dependencies:  ServicesDependencies }) 
dependencies.push({listName : SiteAssetsList,
dependencies:  SiteAssetsDependencies }) 
dependencies.push({listName : SitePagesList,
dependencies:  SitePagesDependencies }) 
dependencies.push({listName : StyleLibraryList,
dependencies:  StyleLibraryDependencies }) 
dependencies.push({listName : UserProfilesList,
dependencies:  UserProfilesDependencies }) 
dependencies.push({listName : UserVoiceList,
dependencies:  UserVoiceDependencies }) 
dependencies.push({listName : UserInformationListList,
dependencies:  UserInformationListDependencies }) 


	return dependencies
}

