
	"use client"
	// ************************************************************
	// Generated by pnp2ts - do not edit .
	// www.koksmat.com
	// v0.1.0
	// ************************************************************

	import Link from "next/link";
	import { Button } from "@/registry/new-york/ui/button";
	import { ShowDefinitions } from "@/app/sharepoint/components/showlistsDefinitions";
import { useContext } from "react";
import { MagicboxContext } from "@/app/magicbox-context";
import { map } from "..";
	


	export default function Page({params}:{params:{site:string}}) {
		const magicbox = useContext(MagicboxContext);
		return (<div>
	
<div>
		<Button variant={"link"}><Link href="./Documents">Documents</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Environments">Environments</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Epics">Epics</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Events">Events</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Features">Features</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./FormTemplates">Form Templates</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Issuetracker">Issue tracker</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Packages">Packages</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./ProblemTracker">Problem Tracker</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Releases">Releases</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Requesttracker">Request tracker</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Services">Services</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./SiteAssets">Site Assets</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./SitePages">Site Pages</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./StyleLibrary">Style Library</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./UserProfiles">User Profiles</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./UserVoice">User Voice</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./UserInformationList">User Information List</Link></Button>		
</div>

	<ShowDefinitions tenant={magicbox.tenant} site={params.site} map={map()} />
	</div>)
}

