
	// ************************************************************
	// Generated by pnp2ts - do not edit .
	// www.koksmat.com
	// v0.1.0
	// ************************************************************

	import Link from "next/link";
	import { Button } from "@/registry/new-york/ui/button";
	
	


	export default function Page() {
	
		return (<div>
	
<div>
		<Button variant={"link"}><Link href="./Buildings">Buildings</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./CateringOrders">Catering Orders</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./CateringOrdersInvoices">Catering Orders Invoices</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./CateringOrdersItems">Catering Orders Items</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./CateringOrdersWorkOrders">Catering Orders Work Orders</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./CateringProviders">Catering Providers</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./CavaSAPreport">Cava SAP report</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Companies">Companies</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Countries">Countries</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Currency">Currency</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Desks">Desks</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Documents">Documents</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Events">Events</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./EventTracking">EventTracking</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Floors">Floors</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./FormTemplates">Form Templates</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./ItemGroups">ItemGroups</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Items">Items</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./KeyValues">Key Values</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Locations">Locations</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./LunchMenu">Lunch Menu</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Pricelists2">Pricelists2</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./RoomSites">Room Sites</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Rooms">Rooms</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./SharedMailboxesOwners">Shared Mailboxes Owners</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./SharedMailboxOwners">SharedMailbox Owners</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./SiteAssets">Site Assets</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./SitePages">Site Pages</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./StyleLibrary">Style Library</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./TestChanges">Test Changes</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./UseCases">Use Cases</Link></Button>		
</div>

<div>
		<Button variant={"link"}><Link href="./Workspaces">Workspaces</Link></Button>		
</div>


	</div>)
}

